"""Add is_confirmed to User

Revision ID: 4ce16f289b99
Revises: 7e49812bcf5a
Create Date: 2025-09-17 00:18:34.308141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ce16f289b99"
down_revision: Union[str, Sequence[str], None] = "7e49812bcf5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("is_confirmed", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_confirmed")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
